### ISSUE TITLE
Not being responsive on window resizing (smaller)

### ISSUE THREAD

**Issue by brspurri** [bradwestfall/react-flex-columns#1]
I see that in the codesandbox examples, that when increasing/decreasing the size of the window, the columns are responsively resized (which is correct).

However, in my implementation, when I increase the window size, the columns are resized correctly, yet when I decrease the size, it fails to reduce the column with responsively.

My code is as follows:

```
    <Columns>
          <Column>
            <h2 className={classes.pending}>{title}</h2>
          </Column>
          <Column flex />
          <Column size={20} className={classes.searchColumnContainer}>
            <div>
              <TextField />
            </div>
          </Column>
          <Column size={15} className={classes.centerAlign}>
            <MyButton />
          </Column>
    </Columns>
```

Is there any reason that the responsiveness might work when increasing the window size, yet fail when decreasing the window size?

**Comment by bradwestfall** [comment]
You'll have to let me know a little more. Not sure if you can make a sandbox to help me see the issue, but I know that might be hard because there's context here with your custom components and styles. It might even be more helpful to provide a gif or something I can see and how it behaves vs how you want it to
